{
 "title": "Victoria Logs Operations",
 "description": "a victoria-logs dashboard",
 "tags": [ "victorialogs" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Select Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Ingested Rows by Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vl_rows_ingested_total{})", "legendFormat": "{{opentelemetry}}" }
   ]
  },
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_streams_created_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(vl_partitions{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data size by storage type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_data_size_bytes{type=\"indexdb\"}) by (type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vl_data_size_bytes{type=\"storage\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingested Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum((rate(vl_rows_ingested_total[$__rate_interval]))) by (type) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(vl_http_request_duration_seconds_bucket{}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request by Path",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(vl_http_requests_total[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(vl_errors_total[$__rate_interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Rows By Reason",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_dropped_total[$__rate_interval])) by (reason)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}