---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-k8s-events
  namespace: otel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-k8s-events
rules:
- apiGroups: [""]
  resources:
  - events
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8s-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-k8s-events
subjects:
  - kind: ServiceAccount
    name: otel-k8s-events
    namespace: otel