operator:
  # -- By default, operator converts prometheus-operator objects.
  disable_prometheus_converter: true

watchNamespaces: ["victoria-logs"]

# -- Resource object
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi

nameOverride: "victoria-metrics-operator"