server:
  enabled: true
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    retentionPeriod: 7d
    retention.maxDiskSpaceUsageBytes: 5GiB
  image:
    tag: "v0.29.0-victorialogs"

  persistentVolume:
    enabled: false
    # size: 5Gi

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi

  serviceMonitor:
    enabled: false

  ingress:
    enabled: false
